### ISSUE TITLE
Don't use `instanceof` on internal `Batch` prototype

### ISSUE THREAD

**Issue by indexzero** [godaddy/node-priam#46]
From the discussion https://github.com/godaddy/node-priam/pull/45#discussion_r25821090

> _indexzero:_ Using `instanceof` on custom prototypes makes working with that prototype more difficult. For example I cannot write a Facade which wraps `Batch` because it isn't the exact same prototype. I wouldn't go as far as to say _"`instanceof` considered harmful"_ (although [other folks have](http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/)), but I generally only use it with prototypes native to the language.
> 
> _scommisso:_ I can sniff whether or not it is a batch a different way. I'll address this.

Feature detection instead of `instanceof` seems like the best way to go.

**Comment by scommisso** [comment]
Completed
