### ISSUE TITLE
ability to specify policies for datastax driver?

### ISSUE THREAD

**Issue by bkw** [godaddy/node-priam#50]
I wonder if it is possible to pass custom options to the datastax driver, an [address resolution policy][1] for example.
Or is there another procedure that I've overlooked to translate cassandra node addresses?

[1]: http://docs.datastax.com/en/developer/nodejs-driver/2.1/nodejs-driver/reference/addressResolution.html

**Comment by scommisso** [comment]
I'm working on getting this library updated to use DataStax 2.1 - should be merged today, hopefully. Anything you pass into `config` when instantiating the driver will get passed along to the DataStax driver. Similarly, anything you pass into `options` when executing a CQL statement will get passed into the DataStax driver. So once I get the new version out, the new policies should be available. Give passing the config properties a shot. If it doesn't work, we'll look at this.

**Comment by bkw** [comment]
Thanks for the response, this does indeed sound interesting. No rush though, I switched to using the datastax driver directly for the time being. I'll check back with Priam as time permits.
